### ISSUE TITLE
Che 7 GA

### ISSUE THREAD

**Issue by gazarenkov** [gazarenkov/che-ide6#22]
From che created by [l0rd](https://github.com/l0rd) : eclipse/che#12696  

## Che 7 GA Details

**Goal:** Release the new version of Che 7 in a GA state, including documentation, automated tests and website updates. 

**User Story 1 (hosted theia plugin dev)**: As a Che developer I want to start a workspace configured to load theia as the editor and an “hello world” frontend theia plugin (using an existing che stack from the dashboard and with the editor and plugins definition available in a remote plugin registry) so that I will be able to easily developing new plugins.

**User Story 2 (java/nodejs dev)**: As a developer using Che, I want to start a workspace that is configured with the tooling that I defined for my NodeJS/Java project (configuring it from the dashboard, or using a devfile on the repository) so that I will be able to develop on my project and get all language tooling.

**User Story 3 (k8s developer experience)**: As a developer working on a K8S application, I want to be able to use the definition of my application (yaml) in order to create a devfile and get a developer workspace for Che which will replicate my application to allow fast iterative development.

**User Story 4 (chectl and operator)**: 
- As an admin of Che (or user using Che locally), I want to use a CLI based tool that is provided with Che to install and configure my Eclipse Che using (using the operator) so that I can easily control my installation.
- As an admin (or user using Che locally) of a kubernetes cluster, I want to use the OperatorHub to proceed the installation of Eclipse Che.

**User Story 5 (k8s plugin basic flow)**: As a developer using Che, I want to interact with my K8S / OpenShift cluster using dedicated plugins, so I can manage my cluster and push my source code onto the cluster.

**User Story 6 (mutli-editors experience)**: 
- As a developer using Che, I want to build my application using my IDE where I can build code and debug it. I can deploy my application onto K8S / OpenShift cluster using dedicated plugins.
- As a different persona (data scientist), I can work on the same application/context with adapted tools for my needs (Jupyter). 

**Che 7 Success Criteria:**
Implementation of the 5 user stories with:
- The user is able to configure the workspace for his project with the tools he wants
- Complete inner loop is working in the new IDE: Code, Build, Run and Debug
- Devfile has the only format exposed to define workspaces (stacks, factories)
- Languages: Java, Node, Typescript, XML, YAML, C#, Go, Python, PHP
- Out of the box stacks and samples updated
- Chectl as a new CLI for Che
- UX refinements for installation of plugins
- UX adaptations in dashboard to cover devfiles and other che 7 new capabilities
- Ability to switch editors
- Easier monitoring and tracing capabilities
- Pull Request plugin

#### BUGS:
We are using the following label to list all the bugs that need a fix for Che 7 GA.
Link to the GitHub request: [Che 7 GA Bugs](https://github.com/eclipse/che/issues?q=is%3Aopen+is%3Aissue+label%3Atarget%2Fche7GA+label%3Akind%2Fbug)

#### IDE2

- [ ] Detect services that are listening to a port and propose to expose it -https://github.com/eclipse/che/issues/12061
- [ ] Sharing from the IDE - https://github.com/eclipse/che/issues/12722
- [ ] Plugin installation UX - https://github.com/eclipse/che/issues/12905
- [ ] Dashboard refinements on Creating a new workspaces - https://github.com/eclipse/che/issues/12896
- [ ] Dashboard refinements on editing a workspace (split editor and plugins) - https://github.com/eclipse/che/issues/12909
- [ ] Dashboard, don't display the list of sample plugins by default - https://github.com/eclipse/che/issues/12910
- [ ] Handle memory configuration - #11801 
- [ ] Mark workspaces in that are not compatible anymore with Che 7 (old Che 6 workspaces) - https://github.com/eclipse/che/issues/12917
- [ ] Handle incompatible factories - https://github.com/eclipse/che/issues/12918
- [ ] Bug fixing: https://github.com/eclipse/che-theia/issues/101 https://github.com/eclipse/che/issues/11866 

#### IDE

- [ ] Che commands should be first class citizens in Theia #12709 
- [ ] Finalize Kubernetes Plugin Support (WIP) https://github.com/eclipse/che/issues/10574
- [ ] Finalize OpenShift Plugin Support https://github.com/eclipse/che/issues/11488
- [ ] Rework Task extension to a plug-in https://github.com/eclipse/che/issues/11458
- [x] wsmaster scalability issues: Output Endpoint https://github.com/eclipse/che/issues/11961 
- [ ] Integration of the GitHub Plugin - https://github.com/eclipse/che/issues/11867 
- [ ] Extend pull request flow to add Factory in the comments - https://github.com/eclipse/che/issues/10282
- [ ] Bug fixing:

#### Languages

- [ ] Scalability Issues (Che-in-Che) https://github.com/eclipse/eclipse.jdt.ls/issues/865
- [x] Integration of Python - https://github.com/eclipse/che/issues/12771
- [ ] Python Stack
- [ ] Integration of C# - https://github.com/eclipse/che/issues/12773
- [ ] C# Stack
- [ ] Integration of PHP - https://github.com/eclipse/che/issues/12772
- [ ] PHP Stack
- [ ] Create new default Stacks and Samples - https://github.com/eclipse/che/issues/12620
- [ ] Integration of Camel Plugin - https://github.com/eclipse/che/issues/12584
- [ ] Bug fixing:

#### OSIO

- [ ] Merge meta.yml and che-plugin.yml - #12908 
- [ ] VS Code marketplace rate limit - #12840
- [ ] Telemetry - https://github.com/eclipse/che/issues/12717
- [ ] Allow to use 'latest' for plugin versions #12937
- [ ] Enforce a better plugin registry naming convention https://github.com/eclipse/che-plugin-registry/issues/55
- [ ] Bug fixing:

#### Platform

- [x] Add more fields to the plug-in registry - https://github.com/eclipse/che-plugin-registry/issues/71
- [ ] Finalize Devfile - https://github.com/eclipse/che/issues/11549
- [ ] Adopt devfile format for Stacks - https://github.com/eclipse/che/issues/12924
- [ ] Adopt devfile format for workspaces - https://github.com/eclipse/che/issues/12926
- [ ] Adopt devfile format for factories - https://github.com/eclipse/che/issues/12925
- [ ] Finalize Monitoring - https://github.com/eclipse/che/issues/10329
- [ ] Finalize Tracing - https://github.com/eclipse/che/issues/10298
- [ ] Bug fixing:

#### Installation

- [ ] Operator for Che 7 on OperatorHub - https://github.com/eclipse/che/issues/11469
- [ ] chectl: OCP support, Docker desktop, Update, Stop and Delete Che

#### QE

- [x] Define the strategy to add tests on Theia (WIP) (Investigate e2e technologies for Thea #12204)
- [ ] Che in Che QE
- [ ] Test for Yeoman Generate plugins
- [ ] Scalability testing (WIP)  

#### Documentation, training and demos

- [ ] Integrate new documentation about extensibility 
- [ ] Port Che6 documentation to Che 7
- [ ] Update README
- [ ] Update Contributing wiki
- [ ] Make some demo/workshop material (doc + short blog post + short video) [github repo](https://github.com/che-incubator/che-demos)
  - [ ] Devfile
  - [ ] New multi container based workspace model
  - [ ] VS Code plugin compatibility
  - [ ] Container based development
  - [ ] chectl
  - [ ] Che operator
  - [ ] Monitoring and Tracing (@ibuziuk)
  - [ ] Editor swapping capability
